[theme]
# Primary accent for interactive elements
primaryColor="#eab308"

# Background color for the main content area
backgroundColor="#020617"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor="#0f172a"

# Color used for almost all text
textColor="#22c55e"
